version: '3.1'

services:
  dialog:
    build: .
    working_dir: /dialog
    tty: true
    ports: 
      - "8000:8000"
    volumes:
      - .:/dialog
    # command: cd web-client && uvicorn main:app --reload --host 0.0.0.0 --port 8000