version: '3.1'

services:
  dialog:
    build: ./web_api
    working_dir: /dialog_api
    tty: true
    ports: 
      - "8000:8000"
    volumes:
      - ./web_api:/dialog_api
    command: sh -c "cd /dialog_api && uvicorn main:app --reload --host 0.0.0.0 --port 8000"

  web_client:
    build: ./web_client
    working_dir: /web_client
    tty: true
    ports: 
      - "3000:3000"
    volumes:
      - ./web_client/app:/web_client
    # command: sh -c "cd /web_client && npm start"