version: '3.1'

services:
  dialog:
    build: ./web_api
    working_dir: /dialog_api
    tty: true
    ports: 
      - "8000:8000"
    volumes:
      - ./web_api:/dialog_api
    command: sh -c "cd /dialog_api && uvicorn main:app --reload --host 0.0.0.0 --port 8000"